version: '3'
services:
  ant-sim-development:
    build:
      context: .
      dockerfile: Dockerfile.Dev
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
    volumes:
      - /app/node_modules
      - .:/app
    restart: always
